import type { ArchitectureModel, Churn, CommitDetail } from '../../shared/studio'

/**
 * A small, hand-written model of a CRM (screens, API, sign-in, services, an AI assistant with three
 * tools, data, background jobs, and four outside services). The tests use it as a realistic input.
 */
export const sampleModel: ArchitectureModel = {
  version: 1,
  repo: { owner: 'exemplo', name: 'crm', branch: 'main', sha: '0a1b2c3d4e5f', private: false },
  generatedAt: '2026-10-01T12:00:00Z',
  stats: {
    files: 186,
    analyzed: 172,
    lines: 21400,
    truncated: false,
    languages: [
      { name: 'Python', files: 96 },
      { name: 'TypeScript', files: 58 },
      { name: 'Outras', files: 18 },
    ],
  },
  summary: {
    en: 'The sales team works in a set of screens that talk to one API. The API checks who is signed in, then reads and changes customers and deals in the database. A sales assistant, built on an AI model, helps with the same data.',
    pt: 'A equipe de vendas trabalha em um conjunto de telas que conversam com uma única API. A API confere quem entrou e então lê e altera clientes e negociações no banco de dados. Um assistente de vendas, feito com um modelo de IA, usa esses mesmos dados para ajudar.',
  },
  components: [
    {
      id: 'frontend/src/pages',
      name: 'Telas',
      path: 'frontend/src/pages',
      direct: false,
      layer: 'interface',
      files: 28,
      lines: 3900,
      tech: ['React', 'TypeScript'],
      entry: true,
      summary: {
        en: 'The screens the sales team uses: dashboard, customers and deals.',
        pt: 'As telas que a equipe de vendas usa: painel, clientes e negociações.',
      },
    },
    {
      id: 'frontend/src/components',
      name: 'Peças de tela',
      path: 'frontend/src/components',
      direct: false,
      layer: 'interface',
      files: 41,
      lines: 2800,
      tech: ['React'],
      entry: false,
      summary: {
        en: 'Buttons, tables and forms reused across the screens.',
        pt: 'Botões, tabelas e formulários reaproveitados entre as telas.',
      },
    },
    {
      id: 'backend/api/routes',
      name: 'Rotas',
      path: 'backend/api/routes',
      direct: false,
      layer: 'api',
      files: 12,
      lines: 1100,
      tech: ['FastAPI'],
      entry: true,
      summary: {
        en: 'The addresses the screens call, and the answers they get back.',
        pt: 'Os endereços que as telas chamam e as respostas que recebem de volta.',
      },
    },
    {
      id: 'backend/auth',
      name: 'Acesso',
      path: 'backend/auth',
      direct: false,
      layer: 'security',
      files: 6,
      lines: 480,
      tech: ['JWT', 'OAuth'],
      entry: false,
      summary: {
        en: 'Checks who is signed in and what each person may see.',
        pt: 'Confere quem entrou e o que cada pessoa pode ver.',
      },
    },
    {
      id: 'backend/services/clientes',
      name: 'Clientes',
      path: 'backend/services/clientes',
      direct: false,
      layer: 'logic',
      files: 9,
      lines: 900,
      tech: ['Python'],
      entry: false,
      summary: {
        en: 'The rules for creating, finding and merging customers.',
        pt: 'As regras para cadastrar, buscar e unir clientes.',
      },
    },
    {
      id: 'backend/services/negocios',
      name: 'Negociações',
      path: 'backend/services/negocios',
      direct: false,
      layer: 'logic',
      files: 8,
      lines: 760,
      tech: ['Python'],
      entry: false,
      summary: {
        en: 'The rules for deals: stages, values and follow-ups.',
        pt: 'As regras das negociações: etapas, valores e retornos.',
      },
    },
    {
      id: 'backend/agents/assistente',
      name: 'Assistente de vendas',
      path: 'backend/agents/assistente',
      direct: false,
      layer: 'ai',
      files: 7,
      lines: 640,
      tech: ['OpenAI', 'Pydantic'],
      entry: false,
      summary: {
        en: 'An AI assistant that answers the sales team and uses three tools to look things up.',
        pt: 'Um assistente de IA que responde a equipe de vendas e usa três ferramentas para consultar informações.',
      },
    },
    {
      id: 'backend/tarefas',
      name: 'Tarefas agendadas',
      path: 'backend/tarefas',
      direct: false,
      layer: 'jobs',
      files: 5,
      lines: 380,
      tech: ['Celery'],
      entry: true,
      summary: {
        en: 'Jobs that run on their own: reminders for follow-ups and the nightly report.',
        pt: 'Trabalhos que rodam sozinhos: lembretes de retorno e o relatório da noite.',
      },
    },
    {
      id: 'backend/modelos',
      name: 'Modelos de dados',
      path: 'backend/modelos',
      direct: false,
      layer: 'data',
      files: 11,
      lines: 720,
      tech: ['SQLAlchemy'],
      entry: false,
      summary: {
        en: 'The shape of every table: customers, deals, users and notes.',
        pt: 'A forma de cada tabela: clientes, negociações, usuários e anotações.',
      },
    },
    {
      id: 'backend/comum',
      name: 'Utilidades',
      path: 'backend/comum',
      direct: false,
      layer: 'shared',
      files: 4,
      lines: 210,
      tech: [],
      entry: false,
      summary: {
        en: 'Small helpers used by everyone: dates, money and error messages.',
        pt: 'Pequenas funções usadas por todos: datas, valores e mensagens de erro.',
      },
    },
    {
      id: 'deploy',
      name: 'Implantação',
      path: 'deploy',
      direct: false,
      layer: 'infra',
      files: 3,
      lines: 140,
      tech: ['Docker'],
      entry: false,
      summary: {
        en: 'How the system is packed and started on the servers.',
        pt: 'Como o sistema é empacotado e iniciado nos servidores.',
      },
    },
    {
      id: 'backend/testes',
      name: 'Testes do servidor',
      path: 'backend/testes',
      direct: false,
      layer: 'tests',
      files: 14,
      lines: 1300,
      tech: ['pytest'],
      entry: false,
      summary: {
        en: 'Automatic checks that the server behaves as expected.',
        pt: 'Verificações automáticas de que o servidor se comporta como esperado.',
      },
    },
  ],
  dependencies: [
    { from: 'frontend/src/pages', to: 'frontend/src/components', weight: 14 },
    { from: 'frontend/src/pages', to: 'backend/api/routes', weight: 18 },
    { from: 'backend/api/routes', to: 'backend/auth', weight: 22 },
    { from: 'backend/api/routes', to: 'backend/services/clientes', weight: 16 },
    { from: 'backend/api/routes', to: 'backend/services/negocios', weight: 12 },
    { from: 'backend/api/routes', to: 'backend/agents/assistente', weight: 5 },
    { from: 'backend/api/routes', to: 'backend/comum', weight: 4 },
    { from: 'backend/services/clientes', to: 'backend/modelos', weight: 13 },
    { from: 'backend/services/negocios', to: 'backend/modelos', weight: 9 },
    { from: 'backend/services/negocios', to: 'backend/services/clientes', weight: 6 },
    { from: 'backend/agents/assistente', to: 'backend/services/clientes', weight: 4 },
    { from: 'backend/agents/assistente', to: 'backend/services/negocios', weight: 3 },
    { from: 'backend/tarefas', to: 'backend/services/negocios', weight: 4 },
    { from: 'backend/tarefas', to: 'backend/comum', weight: 2 },
    { from: 'backend/auth', to: 'backend/modelos', weight: 3 },
    { from: 'backend/modelos', to: 'backend/comum', weight: 2 },
    { from: 'backend/testes', to: 'backend/services/clientes', weight: 5 },
    { from: 'backend/testes', to: 'backend/api/routes', weight: 6 },
  ],
  externals: [
    { id: 'postgres', name: 'PostgreSQL', kind: 'database', usedBy: ['backend/modelos'] },
    { id: 'redis', name: 'Redis', kind: 'cache', usedBy: ['backend/auth', 'backend/api/routes'] },
    { id: 'openai', name: 'OpenAI', kind: 'llm', usedBy: ['backend/agents/assistente'] },
    { id: 'sendgrid', name: 'SendGrid', kind: 'email', usedBy: ['backend/tarefas'] },
  ],
  endpoints: [
    { method: 'GET', path: '/clientes', file: 'backend/api/routes/clientes.py', line: 12, component: 'backend/api/routes' },
    { method: 'POST', path: '/clientes', file: 'backend/api/routes/clientes.py', line: 30, component: 'backend/api/routes' },
    { method: 'GET', path: '/negocios', file: 'backend/api/routes/negocios.py', line: 10, component: 'backend/api/routes' },
    { method: 'PATCH', path: '/negocios/{id}', file: 'backend/api/routes/negocios.py', line: 41, component: 'backend/api/routes' },
    { method: 'POST', path: '/login', file: 'backend/auth/login.py', line: 8, component: 'backend/auth' },
    { method: 'POST', path: '/assistente/mensagens', file: 'backend/api/routes/assistente.py', line: 21, component: 'backend/api/routes' },
  ],
  agents: [
    {
      id: 'assistente',
      name: 'Assistente de vendas',
      file: 'backend/agents/assistente/agente.py',
      component: 'backend/agents/assistente',
      provider: 'OpenAI',
      model: 'gpt-4o-mini',
      framework: 'OpenAI Agents SDK',
      instructions:
        'Você ajuda vendedores a encontrar clientes e negociações. Use as ferramentas quando precisar de dados e nunca invente valores. Antes de anotar um retorno, peça confirmação.',
      tools: [
        {
          name: 'buscar_cliente',
          description: 'Procura um cliente pelo nome ou pelo e-mail.',
          file: 'backend/agents/assistente/ferramentas.py',
          line: 14,
        },
        {
          name: 'listar_negocios',
          description: 'Lista as negociações abertas de um cliente.',
          file: 'backend/agents/assistente/ferramentas.py',
          line: 33,
        },
        {
          name: 'registrar_retorno',
          description: 'Anota um retorno feito ao cliente.',
          file: 'backend/agents/assistente/ferramentas.py',
          line: 52,
        },
      ],
      graph: {
        explicit: false,
        nodes: [
          { id: 'inicio', label: 'Vendedor envia uma mensagem', kind: 'start' },
          { id: 'instrucoes', label: 'Instruções do assistente', kind: 'instructions' },
          { id: 'modelo', label: 'Modelo lê a conversa e decide', kind: 'llm' },
          { id: 'decide', label: 'Precisa de dados ou de uma ação?', kind: 'decision' },
          { id: 'buscar', label: 'buscar_cliente', kind: 'tool', file: 'backend/agents/assistente/ferramentas.py', line: 14 },
          { id: 'listar', label: 'listar_negocios', kind: 'tool', file: 'backend/agents/assistente/ferramentas.py', line: 33 },
          { id: 'registrar', label: 'registrar_retorno', kind: 'tool', file: 'backend/agents/assistente/ferramentas.py', line: 52 },
          { id: 'confirmar', label: 'Vendedor confirma antes de salvar', kind: 'human' },
          { id: 'fim', label: 'Responde ao vendedor', kind: 'end' },
        ],
        links: [
          { from: 'inicio', to: 'modelo', condition: null },
          { from: 'instrucoes', to: 'modelo', condition: null },
          { from: 'modelo', to: 'decide', condition: null },
          { from: 'decide', to: 'buscar', condition: 'precisa de um cliente' },
          { from: 'decide', to: 'listar', condition: 'quer ver negociações' },
          { from: 'decide', to: 'registrar', condition: 'quer anotar um retorno' },
          { from: 'decide', to: 'fim', condition: 'basta responder' },
          { from: 'buscar', to: 'modelo', condition: null },
          { from: 'listar', to: 'modelo', condition: null },
          { from: 'registrar', to: 'confirmar', condition: null },
          { from: 'confirmar', to: 'modelo', condition: 'confirmado' },
        ],
      },
      loop: true,
    },
  ],
  flows: [
    {
      id: 'assistente',
      kind: 'agent',
      title: { en: 'The assistant decides', pt: 'O assistente decide' },
      summary: {
        en: 'A salesperson asks a question, and the assistant chooses whether to look something up first.',
        pt: 'Um vendedor faz uma pergunta, e o assistente escolhe se antes precisa consultar alguma coisa.',
      },
      actors: [
        {
          id: 'vendedor',
          name: { en: 'Salesperson', pt: 'Vendedor' },
          kind: 'person',
          component: null,
          external: null,
          note: { en: 'Writes to the assistant', pt: 'Escreve para o assistente' },
        },
        {
          id: 'assistente',
          name: { en: 'Sales assistant', pt: 'Assistente de vendas' },
          kind: 'agent',
          component: 'backend/agents/assistente',
          external: null,
          note: { en: 'Decides what to do next', pt: 'Decide o que fazer em seguida' },
        },
        {
          id: 'busca',
          name: { en: 'Customer search', pt: 'Busca de clientes' },
          kind: 'tool',
          component: 'backend/services/clientes',
          external: null,
          note: { en: 'Finds customers by name', pt: 'Encontra clientes pelo nome' },
        },
        {
          id: 'modelo',
          name: { en: 'AI model', pt: 'Modelo de IA' },
          kind: 'llm',
          component: null,
          external: 'openai',
          note: { en: 'Reads the conversation', pt: 'Lê a conversa' },
        },
      ],
      steps: [
        { from: 'vendedor', to: 'assistente', action: 'ask', text: { en: 'The salesperson asks about a customer.', pt: 'O vendedor pergunta sobre um cliente.' }, say: { en: 'Who is Ana?', pt: 'Quem é a Ana?' } },
        { from: 'assistente', to: 'modelo', action: 'think', text: { en: 'The assistant reads its instructions and the question.', pt: 'O assistente lê suas instruções e a pergunta.' } },
        { from: 'assistente', to: 'assistente', action: 'decide', text: { en: 'It decides it needs to look the customer up.', pt: 'Ele decide que precisa consultar a cliente.' } },
        { from: 'assistente', to: 'busca', action: 'use-tool', text: { en: 'It calls the customer search.', pt: 'Ele chama a busca de clientes.' } },
        { from: 'busca', to: 'assistente', action: 'reply', text: { en: 'The search sends back the customer.', pt: 'A busca devolve a cliente encontrada.' } },
        { from: 'assistente', to: 'vendedor', action: 'show', text: { en: 'The answer appears on the salesperson\'s screen.', pt: 'A resposta aparece na tela do vendedor.' } },
      ],
    },
  ],
}

/** The first agent of the sample, the one whose decision graph the tests draw. */
export const sampleAgent = sampleModel.agents[0]

/** Churn over the last commits: the customer and deal code changes the most. */
export const sampleChurn: Churn = {
  files: [
    { path: 'backend/services/clientes/servico.py', commits: 14, additions: 420, deletions: 130 },
    { path: 'backend/api/routes/negocios.py', commits: 11, additions: 300, deletions: 90 },
    { path: 'frontend/src/pages/Clientes.tsx', commits: 9, additions: 260, deletions: 80 },
    { path: 'backend/agents/assistente/agente.py', commits: 6, additions: 150, deletions: 40 },
    { path: 'backend/modelos/cliente.py', commits: 5, additions: 70, deletions: 20 },
    { path: 'backend/auth/login.py', commits: 3, additions: 40, deletions: 10 },
  ],
  commits: 40,
  filters: {},
}

/** One commit that touched the assistant, the customer rules and a screen. */
export const sampleCommit: CommitDetail = {
  sha: '0a1b2c3d4e5f6071',
  headline: 'Acrescenta retorno automático ao assistente',
  body: '',
  author: { name: 'Ana Souza', login: 'ana', avatarUrl: null },
  date: '2026-09-28T15:20:00Z',
  parents: 1,
  url: 'https://github.com/exemplo/crm/commit/0a1b2c3d4e5f6071',
  stats: { additions: 34, deletions: 6, total: 40 },
  files: [
    { path: 'backend/agents/assistente/agente.py', previousPath: null, status: 'modified', additions: 20, deletions: 4, patch: null, truncated: false },
    { path: 'backend/services/clientes/servico.py', previousPath: null, status: 'modified', additions: 9, deletions: 2, patch: null, truncated: false },
    { path: 'frontend/src/pages/Clientes.tsx', previousPath: null, status: 'modified', additions: 5, deletions: 0, patch: null, truncated: false },
  ],
  filesTruncated: false,
}
